services:
  ecommerce-db:
    image: ecommerce-db
    build:
      context: ../database
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ecommerce-data:/var/lib/postgresql/data
    networks:
      - ecommerce

  ecommerce-service:
    image: ecommerce-service
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ../:/usr/src/app
    depends_on:
      - ecommerce-db
    ports:
      - 4000:80
      - 11000:11000
    environment:
      - ENVIRONMENT=dev
      - APP_TITLE=FastAPI Ecommerce App
      - APP_DESCRIPTION=Ecommerce App using FastAPI and SQLAlchemy
      - APP_VERSION=0.1.0
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=http://ecommerce-db:5432
      - DATABASE_NAME=ecommerce-db
      - TEST_DATABASE_NAME=ecommerce-test-db
    networks:
      - ecommerce

volumes:
  ecommerce-data:
    external: true

networks:
  ecommerce:
    external: true
